### ISSUE TITLE
Cannot disable auto-discovery

### ISSUE THREAD

**Issue by denitsa-cm** [rollbar/rollbar-php-laravel#60]
I want to disable auto-discovery and register the service provider manually since I don't want rollbar on development. I tried doing it but to no avail.

I read the docs here https://docs.rollbar.com/docs/laravel#section-installation. 

I have the following entry in my `composer.json`

```
  "extra": {
    "laravel": {
      "dont-discover": [
        "rollbar/rollbar-laravel"
      ]
    }
```

I have the following in my `AppServiceProvider:register()`:

```
        if ($this->app->environment(['staging', 'production'])) {
            $this->app->register(\Rollbar\Laravel\RollbarServiceProvider::class);
        }
```

I have version:

```
            "name": "rollbar/rollbar-laravel",
            "version": "v4.0.0",
```

I've also run `php artisan package:discover` after the update to composer.json and the package is correctly not present in `Discovered package:` lines that are generated from the command.

My temporary solution is to remove the `ROLLBAR_TOKEN` from my local `.env` file.

Is there something I'm missing?

**Comment by jessewgibbs** [comment]
Hi denitsa-cm,

We'll get one of our library maintainers to take a look at your question and respond soon.

**Comment by nickbryan** [comment]
@ArturMoczulski any update on this?

**Comment by kedarv** [comment]
I can confirm that this is an issue on Laravel 5.6 with the latest dist version of this package. In composer.json I have
```
    "extra": {
        "laravel": {
            "dont-discover": [
                "rollbar/rollbar-laravel"
            ]
        }
    },
```

and I've confirmed via `php artisan package:discover` that `"rollbar/rollbar-laravel"` is _not_ in the output. But even then, it looks like things are still being logged somehow. going to dig into it more soon.

**Comment by kedarv** [comment]
This turned out to be an easy fix. The [documentation](https://docs.rollbar.com/docs/laravel) just needs to be more explicit if you're copy pasting from the instructions. To resolve, just remove `        Rollbar\Laravel\RollbarServiceProvider::class,` from your providers array in `config/app.php`

Then, conditionally load the provider in your AppServiceProvider.

As we can [see here](https://github.com/laravel/framework/blob/ce0e5dfd52384a9f333c2ba7a29d8e0394598374/src/Illuminate/Foundation/Application.php#L540), Laravel will attempt to register every service provider in the array in `config/app.php`

Hope this helps!

**Comment by ArturMoczulski** [comment]
Great! Thanks @kedarv I'll amend the docs right now
